# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: "Install docker cli"
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: "Build and publish docker images"
  inputs:
    containerRegistry: $(RegistryServiceConnection)
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: CopyFiles@2
  displayName: "Copy deployment scripts to artifact staging"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AzureDeploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AzureDeploy'

- task: PublishBuildArtifacts@1
  displayName: "Publish build artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'