pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DockerInstaller@0
    displayName: "Install docker cli"
    inputs:
      dockerVersion: "17.09.0-ce"

  - task: Docker@2
    displayName: "Build and publish docker images"
    inputs:
      containerRegistry: $(RegistryServiceConnection)
      repository: "graphroots"
      command: "build"
      Dockerfile: "**/Dockerfile"
