trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  displayName: "Install docker cli"
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: "Build and publish docker images"
  inputs:
    containerRegistry: $(RegistryServiceConnection)
    repository: "graphroots"
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Bash@3
  inputs:
    filePath: '$(Build.SourcesDirectory)/create-config-file.sh'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CopyFiles@2
  displayName: "Copy Environment Config"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '.env'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: "Copy deployment scripts to artifact staging"
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AzureDeploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AzureDeploy'

- task: PublishBuildArtifacts@1
  displayName: "Publish build artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'