version: "3.7"
services:
  redis:
    image: redis:alpine
  webapp:
    build:
      context: .
      args:
        PORT: 4000
    ports:
      - "4000:4000"
    secrets:
      - source: configuration
        target: .env
secrets:
  configuration:
    file: .env
