version: "3.7"
services:
  redis:
    image: redis:alpine
  webapp:
    image: roseitzdevgraphrootsacr.azurecr.io/graphroots:${BUILD_ID}
    ports:
      - "4000:4000"
    secrets:
      - source: configuration
        target: .env
secrets:
  configuration:
    file: .env
