version: "3.7"
services:
  webapp:
    image: roseitzdevgraphrootsacr.azurecr.io/graphroots:#{Build.BuildId}#
    ports:
      - "4000:4000"
    secrets:
      - source: configuration
        target: .env
  redis:
    image: roseitzdevgraphrootsacr.azurecr.io/redis:alpine
secrets:
  configuration:
    file: .env
